In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn

In [3]:
df = pd.read_csv('data/data.csv')
df['Dates'] = pd.DatetimeIndex(df['Dates'])
df.set_index(['Dates'], inplace=True)
df

Q1  Q2  Q3  Q4  Q5
Dates                         
2021-01-01   0   0   4   5   6
2021-01-02   0   9   9   0   0
2021-01-03   3   6   9   8   6
2021-01-04   0   0   0   0   0
2021-01-05   6   7   8   9   0
2021-01-06   0   0   0   0   8

In [4]:
df_fake = df.cumsum(axis=1)
df_fake


Q1  Q2  Q3  Q4  Q5
Dates                         
2021-01-01   0   0   4   9  15
2021-01-02   0   9  18  18  18
2021-01-03   3   9  18  26  32
2021-01-04   0   0   0   0   0
2021-01-05   6  13  21  30  30
2021-01-06   0   0   0   0   8

In [5]:

df_fake = df_fake.replace(0, np.nan)
df_fake

Q1    Q2    Q3    Q4    Q5
Dates                                  
2021-01-01  NaN   NaN   4.0   9.0  15.0
2021-01-02  NaN   9.0  18.0  18.0  18.0
2021-01-03  3.0   9.0  18.0  26.0  32.0
2021-01-04  NaN   NaN   NaN   NaN   NaN
2021-01-05  6.0  13.0  21.0  30.0  30.0
2021-01-06  NaN   NaN   NaN   NaN   8.0

In [6]:
df_numpy = df_fake.values
df_numpy

array([[nan, nan,  4.,  9., 15.],
       [nan,  9., 18., 18., 18.],
       [ 3.,  9., 18., 26., 32.],
       [nan, nan, nan, nan, nan],
       [ 6., 13., 21., 30., 30.],
       [nan, nan, nan, nan,  8.]])

In [7]:
'''ind = np.argwhere(np.isnan(df_numpy))
ind'''

'ind = np.argwhere(np.isnan(df_numpy))\nind'

In [8]:
df_original = df.values
df_original

array([[0, 0, 4, 5, 6],
       [0, 9, 9, 0, 0],
       [3, 6, 9, 8, 6],
       [0, 0, 0, 0, 0],
       [6, 7, 8, 9, 0],
       [0, 0, 0, 0, 8]])

In [9]:
indices = np.where(df_fake.isna())
indices

(array([0, 0, 1, 3, 3, 3, 3, 3, 5, 5, 5, 5]),
 array([0, 1, 0, 0, 1, 2, 3, 4, 0, 1, 2, 3]))

In [14]:
df_original = df_original.astype('float')
for i in zip(indices[0], indices[1]):
    df_original[i] = np.nan

In [11]:
df_original

array([[nan, nan,  4.,  5.,  6.],
       [nan,  9.,  9.,  0.,  0.],
       [ 3.,  6.,  9.,  8.,  6.],
       [nan, nan, nan, nan, nan],
       [ 6.,  7.,  8.,  9.,  0.],
       [nan, nan, nan, nan,  8.]])

In [12]:
df[:] = df_original

In [13]:
df

Q1   Q2   Q3   Q4   Q5
Dates                              
2021-01-01  NaN  NaN  4.0  5.0  6.0
2021-01-02  NaN  9.0  9.0  0.0  0.0
2021-01-03  3.0  6.0  9.0  8.0  6.0
2021-01-04  NaN  NaN  NaN  NaN  NaN
2021-01-05  6.0  7.0  8.0  9.0  0.0
2021-01-06  NaN  NaN  NaN  NaN  8.0